[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "game"
version = "0.0.1"
authors = [
  { name="Dima", email="dima@dima.com" },
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src/game"