name: Trigger auto deployment for python-game

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/python-game-AutoDeployTrigger-57ec0621-cd45-43cb-9d56-8b8a88ad74ac.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PYTHONGAME_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PYTHONGAME_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PYTHONGAME_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.PYTHONGAME_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PYTHONGAME_REGISTRY_PASSWORD }}
          containerAppName: python-game
          resourceGroup: yeshdmits
          imageToBuild: yeshdmits/python-game:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


